config/routes.rb
Rails.application.routes.draw do
  root "events#index"

  get "home", to: "pages#home"

  devise_for :users
  resources :events do
    resources :attendees_events, only: [:new, :create, :destroy]
    member do
      get "join"
      get "leave"
    end
  end

  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendees_event.rb
class AttendeesEvent < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :event, class_name: 'Event'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User", foreign_key: "user_id"
  has_many :attendees_events, dependent: :destroy
  has_many :attendees, through: :attendees_events, dependent: :destroy
  
  validates :title, presence: true, length: { in: 3..50 }
  validates :description, presence: true, length: { in: 3..400 }
  validates :date, :location, presence: true

  scope :past, -> { where("date < ?", Time.current).order(date: :desc) }
  scope :upcoming, -> { where("date > ?", Time.current).order(:date) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :created_events, foreign_key: :user_id, class_name: "Event", dependent: :destroy
  has_many :attendees_events, foreign_key: :attendee_id, dependent: :destroy
  has_many :attended_events, through: :attendees_events, source: :event, dependent: :destroy
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password])

      devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password]) 
    end
end

app/controllers/attendees_events_controller.rb
class AttendeesEventsController < ApplicationController
  
  private

    def attendees_event_params
      params.require(:attendees_event).permit(:event_id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_event, only: [:show, :edit, :update, :destroy]


  def index
    @events = Event.all
  end

  def join
    @event = Event.find(params[:id])

    attendees_events = AttendeesEvent.new(attendee_id: current_user.id, event_id: @event.id)
    if attendees_events.save
      redirect_to @event, notice: "You signed up for the event!"
    else
      redirect_to @event, alert: "You are already signed up for this event!"
    end
  end

  def leave
    @event = Event.find(params[:id])
    attendees_events = AttendeesEvent.find_by(attendee_id: current_user.id, event_id: @event.id)
    attendees_events.destroy

    redirect_to @event, notice: "You are no longer participating in this event!"
  end

  def show
    
  end

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to root_path
      flash[:notice] = "Created Successfully"
    else
      render "new"
      flash.now[:alert] = "Something went wrong"
    end
  end

  def edit
    
  end

  def update
    
    if @event.update(event_params)
      redirect_to @event
      flash[:notice] = "Updated Successfully"
    else
      render :edit
      flash.now[:alert] = "Something went wrong"
    end
  end

  def destroy
    
    @event.destroy

    redirect_to root_path
    flash[:notice] = "Deleted Successfully"
  end


  private

    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :description, :date, :location)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def index
    @users = User.all
  end

  def show

  end

  private

  def set_user
    @user = User.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with model: event, local: true do |f| %>
  <% if event.errors.any? %>
    <ul>
      <% event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: "form-label" %> <br>
    <%= f.text_field :title, placeholder: "Event Title", autofocus: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description, class: "form-label" %> <br>
    <%= f.text_area :description, placeholder: "Event Description", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :location, class: "form-label" %> <br>
    <%= f.text_field :location, placeholder: "Event Location", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :date, class: "form-label" %> <br>
    <%= f.datetime_field :date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-outline-dark mb-2 mt-2" %>
  </div>

<% end %>

app/views/events/edit.html.erb
<div class="container form-background">
  <div class="row align-items-center">
    <div class="col">

      <h1>Edit Event</h1>
      <%= render "form", event: @event %>

    </div>
    <div class="col ">
      <%= image_tag "edit.png", class: "edit-image" %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<section id="main-image">
  <div class="container">
      <h3 class="main-text">
      Ready. <br> To. <br> Plan.
      </h3>
  </div>
</section>

<div class="row mt-2">
  <div class="col">
    <h1>Upcoming Events</h1>
  </div>
  <div class="col">
    <div class="spinner-border float-end mt-4" role="status">
      <span class="visually-hidden">Loading...</span>
    </div>
  </div>
</div>


<div class="container text-center">
  <div class="row mb-5">
    <% @events.upcoming.each do |event| %>
      <div class="col-md-4 mb-4">
        <div class="card text-bg-light mb-3" style="max-width: 18rem;">
          <div class="card-header"><%= event.title %></div>
          <div class="card-body">
            <p class="card-text mb-2 mt-2"><%= event.description.truncate(100) %></p>
          </div>
          <div class="card-footer text-muted">
            <small>Event Date: <%= event.date.strftime("%B %-d, %Y") %></small> <br>
            <%= link_to "Read more", event_path(event), class: "btn btn-outline-success btn-sm mb-2 mt-2" %>
          </div> 
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="row mb-4 mt-4">
  <div class="col">
    <h2>Past Events</h1>
  </div>
</div>

<div class="container text-center">
  <div class="row mb-5">
    <% @events.past.each do |event| %>
      <div class="col-md-4 mb-4">
        <div class="card text-bg-dark mb-3" style="max-width: 18rem;">
          <div class="card-header"><%= event.title %></div>
          <div class="card-body">
            <p class="card-text mb-2 mt-2"><%= event.description.truncate(100) %></p>
          </div>
          <div class="card-footer text-muted">
            <small>Event Date: <%= event.date.strftime("%B %-d, %Y") %></small> <br>
            <%= link_to "Read more", event_path(event), class: "btn btn-outline-success btn-sm mb-2 mt-2" %>
          </div> 
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= form_with model: @event, local: true do |f| %>
  <% if @event.errors.any? %>
    <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: "label" %> <br>
    <%= f.text_field :title, placeholder: "Event Title", autofocus: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description, class: "label" %> <br>
    <%= f.text_area :description, placeholder: "Event Description", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :location, class: "label" %> <br>
    <%= f.text_field :location, placeholder: "Event Location", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :date, class: "label" %> <br>
    <%= f.datetime_field :date, class: "form-control" %>
  </div>

  <div class="form-control">
    <%= f.submit class: "btn btn-outline-dark" %>
  </div>

<% end %>

app/views/events/show.html.erb
<div class="row mb-4 mt-2">
  <div class="col-lg-10">
    <h1><%= @event.title %></h1>
  </div>
  <div class="col-lg-2">
    <% if current_user == @event.creator %>
      <%= link_to "Edit", edit_event_path, class: "btn btn-outline-dark mt-4 mx-2 ms-auto" %>
      <%= link_to "Delete", edit_event_path, class: "btn btn-outline-danger mt-4 ms-auto" %>
    <% end %>
  </div>
</div>

<div class="row mb-4">
  <div class="col">
    <div class="card">
      <div class="row no-gutters">
        <div class="col-md-8">
          <div class="card-body">
            <p class="card-text text-muted"> <%= @event.description %> </p>
          </div>
        </div>

        <div class="col-md-4">
          <div class="card-body">
            <p class="text-muted">
              <%= icon('fa-solid text-dark', 'user') %>
              Hosted by: <strong><%= @event.creator.username %></strong>
            </p>
            <p class="text-muted">
              <%= icon('fa-solid text-dark', 'calendar') %>
              Date & Time: <strong><%= @event.date.strftime("%B %-d, %Y at %l:%M %p") %></strong>
            </p>
            <p class="text-muted">
              <%= icon('fa-solid text-dark', 'map-marker') %>
              Location: <strong><%= @event.location %></strong>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<% if @event.date.past? %>
  <%= link_to "The event has ended", root_path, class: "btn btn-danger d-grid gap-2 col-3 ms-auto disabled"%>
<% else %>
  <% if @event.attendees.include?(current_user) %>
    <%= link_to "Leave Event", leave_event_path(@event.id), class: "btn btn-danger d-grid gap-2 col-3 ms-auto" %>
  <% else %>
    <%= link_to "Join Event", join_event_path(@event.id), class: "btn btn-dark d-grid gap-2 col-3 ms-auto" %>
  <% end %>
<% end %>

<% if @event.attendees.empty? %>
<ul class="list-group">
  <li class="list-group-item active mb-4 col-6">This event has no attendees yet!</li>
</ul>
<% else %>
  <h3>Attendees</h3>
    <ul class="list-group list-group-flush col-6">
    <% @event.attendees.each do |attendee| %>
      <li class="list-group-item mb-4"><%= attendee.username %></li>
    <% end %>
  </ul>
<% end %>


app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-3">
    <div class="container text-center">
      <small>&copy; Copyright 2022 Damian Wieszczak</small>
    </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Private-Events", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown me-2">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Profile
              <%= icon('fa-solid', 'user') %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
              <li><hr class="dropdown-divider"></li>
              <%= link_to "Logout", destroy_user_session_path, class: "dropdown-item", data: { turbo_method: :delete } %>
            </ul>
          </li>
          <li class="nav-item">
            <%= link_to "New Event", new_event_path, class: "nav-link-active btn btn-outline-dark mr-2" %>
          </li>
        <% else %>
          <%= link_to "Login", new_user_session_path, class: "btn btn-outline-dark me-2" %>
          <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-dark" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <%= render "shared/messages" %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<%= link_to "Test", root_path, class: "btn btn-success" %>

app/views/shared/_messages.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show m-2" role="alert">
    <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end%>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-2" role="alert">
    <%= alert %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end%>

app/views/users/show.html.erb
<h1>User <%= @user.username %></h1>

<% if @user.created_events.empty? %>
  <p>User has no events</p>
<% else %>
  <% @user.created_events.each do |event| %>
    <%= event.title %><br>
    <%= event.description %>
  <% end %>
<% end %>

<%= link_to "Create Event", new_event_path %>